sudo: required
language: csharp
mono:
- latest
before_install:
- rvm install ruby-2.2.1
- rvm --default use 2.2.1
- jdk_switcher use oraclejdk8
- curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
- sudo apt-get install -y nodejs
- sudo npm install -g n
- sudo n lts
- . $HOME/.nvm/nvm.sh
- nvm install stable
- nvm use stable
- sudo apt-get install curl php5-cli git php5-curl
- curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin
  --filename=composer
- sudo add-apt-repository ppa:cwchien/gradle -y
- sudo apt-get update
- sudo apt-get install python-dev python-pip build-essential
- sudo pip install --upgrade pip
- sudo apt-get install gradle -y --force-yes
- sudo apt-get install ca-certificates
install:
- gem install json
- gem install colorize
- git clone https://github.com/TwilioDevEd/twilio-api-faker.git
- sudo cp twilio-api-faker/keystore/twilio_fake.pem /usr/local/share/ca-certificates/twilio_fake.crt
- sudo update-ca-certificates
script:
- cd twilio-api-faker
- sudo gradle run </dev/null &>/dev/null &
- cd ..
- sleep 25
- ruby tools/snippet-testing/snippet_tester.rb -i
env:
  global:
  - NODE_PATH=/usr/local/lib/node_modules
  - NODE_TLS_REJECT_UNAUTHORIZED=0
  - FAKE_CERT_PATH=~/build/TwilioDevEd/api-snippets/twilio-api-faker/keystore/twilio_fake.pem
  - GRADLE_OPTS="-Dorg.gradle.daemon=true"
  - BASH=/bin/bash
  - BASH_SOURCE=/usr/local/bin/virtualenvwrapper.sh
addons:
  hosts:
    - api.twilio.com
    - taskrouter.twilio.com
    - pricing.twilio.com
    - lookups.twilio.com
